<a href="https://colab.research.google.com/github/LiYingjie-21/WELLCOME-shop-information-analysis/blob/main/WELLCOME_analysis.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [5]:
import pandas as pd
import numpy as np
df=pd.read_excel("/content/LiYingjie_25D027_WELLCOME_Store_Information.xlsx")
LiYingjie_25D027_WELLCOME_DF=df
df

,Store Name,Address,Floor,Number,Operating_Hours,Building_Name
0,Victoria Centre,"No.15 Watson Road, North Point, H.K.",G/F,3105 1578,08:00-22:00,Victoria Centre
1,Mercury Street,"28 Mercury Street, North Point, H.K.",G/F,2571 4869,08:00-22:00,Supernova Stand
2,Fortress Metro Tower,"238 King’s Road, H.K.",G/F,2571 6421,08:00-23:00,Fortress Metro Tower
3,City Garden,"7-14 , City Garden , No. 233 Electrial Road , ...",30-33 Ground Floor,3580 7319,08:30-22:00,Commerial Podiums Below Block
4,North Point,"338 King's Road, North Point, H.K.",G/F,2508 6197,08:00-22:00,Two Chinachem Exchange Square
5,Metropole,"No. 416-426 King's Road, North Point, H.K.",Portion of Basement,2564 0803,08:00-23:00,Metropole Building
6,Island Lodge,"61 & 63 Marble Rd, North Point, H.K.",G/F,2814 8365,08:30-22:00,Island Lodge
7,Fitfort,"560 King's Road, North Point, H.K.",G/F,3583 4260,08:30-22:01,Fitfort
8,Healthy Village,"188 Tsat Tsz Mui Road, North Point, H.K.","(Portion), UG/F",2214 0344,08:00-22:00,Healthy Village I Development
9,Gold Luck,"989-992 King's Road, Quarry Bay, H.K.",Upper Ground Floor,2115 9934,08:00-23:00,Gold Luck
10,Park Vale,"No.1060 King's Road, Quarry Bay, H.K.",Upper Grond Floor,2109 3393,08:00-23:00,Park Vale
11,Kornhill,"18 Hong Shing Street, Kornhill, H.K.",G/F,2885 0337,08:00-21:00,Kornhill Plaza
12,Tai Shan,"Tai Koo Shing, Hong Kong",G/F,2885 3216,08:00-22:00,Tin Shan Mansion
13,Upper East,"18 Shing On Street, Sai Wan Ho, H.K.",G/F,2567 1021,08:30-21:30,18 Upper East
14,Tai On Building,"No. 57/87 Shau Kei Wan Road, H.K.",G26 - G31 (Portion) on Ground Floor,2576 5708,08:00-22:00,Tai On Building
15,Lei King Wan,"35 Tai Hong Street, Sai Wan Ho, H.K.",GC19-21,2815 6029,08:00-21:00,Lei King Wan
16,Yiu Tung,"12 Yiu Hing Road, Shaukeiwan, H.K.","S6A, S6B& S6C (partion), G/F",2663 4818,08:00-21:30,"Yiu Tung Shopping Centre, Yiu Tung Estate"
17,Sun Sing,"245-247 Shaukeiwan Road, Shaukeiwan, H.K.",G/F & M/F,2567 1325,08:30-22:00,Sun Sing Building
18,Harmony Place,"333 Shau Kei Wan Road, H.K.",2/F,2997 9423,08:30-21:00,Harmony Place
19,Aldrich Garden,"No.2 Oi Lai Street, Shau Kei Wan, H.K.",1/F,2818 5837,08:00-21:30,Sldrich garden
20,Perfect Mount,"1 Po Man Street, Shaukeiwan, H.K.",G/F,2567 1549,08:00-23:00,Perfect Mount Garden
21,Fung Wah,"Fung Wah Estate, Chai Wan, H.K.",G/F,2505 2734,08:00-20:30,Hiu Fung House
22,Hing Wah,"Hing Wah Estate II, Chai Wan, H.K.",Upper Floor (portion),2558 2909,09:00-20:30,Restaurant Block
23,Ko Way,"No 111 Chai Wan Road, H.K.",1/F,2558 9728,08:30-21:30,Eastern Plaza
24,Winner,"333 Chai Wan Road, H.K.",Basement,2896 3032,09:00-20:00,Winner Centre
25,Wan Tsui,"Wan Tsui Estate, Chai Wan, H.K.",3/F,2505 1446,08:00-22:00,Wan Tsui Commercial Complex
26,Siu Sai Wan,"Siu Sai Wan Estate, Siu Sai Wan Road, Chai Wan...",2/F,3755 0471,08:00-23:00,Siu Sai Wan Plaza

In [7]:
LiYingjie_25D027_NP=np.array(LiYingjie_25D027_WELLCOME_DF["Store Name"])
print(LiYingjie_25D027_NP)

['Victoria Centre' 'Mercury Street' 'Fortress Metro Tower' 'City Garden'
 'North Point' 'Metropole' 'Island Lodge' 'Fitfort' 'Healthy Village'
 'Gold Luck' 'Park Vale' 'Kornhill' 'Tai Shan' 'Upper East'
 'Tai On Building' 'Lei King Wan' 'Yiu Tung' 'Sun Sing' 'Harmony Place'
 'Aldrich Garden' 'Perfect Mount' 'Fung Wah' 'Hing Wah' 'Ko Way' 'Winner'
 'Wan Tsui' 'Siu Sai Wan']

In [10]:
LiYingjie_25D027_dict=dict(zip(
        LiYingjie_25D027_WELLCOME_DF["Store Name"],
        LiYingjie_25D027_WELLCOME_DF["Operating_Hours"]
))
print(LiYingjie_25D027_dict)

{'Victoria Centre': '08:00-22:00', 'Mercury Street': '08:00-22:00', 'Fortress Metro Tower': '08:00-23:00', 'City Garden': '08:30-22:00', 'North Point': '08:00-22:00', 'Metropole': '08:00-23:00', 'Island Lodge': '08:30-22:00', 'Fitfort': '08:30-22:01', 'Healthy Village': '08:00-22:00', 'Gold Luck': '08:00-23:00', 'Park Vale': '08:00-23:00', 'Kornhill': '08:00-21:00', 'Tai Shan': '08:00-22:00', 'Upper East': '08:30-21:30', 'Tai On Building': '08:00-22:00', 'Lei King Wan': '08:00-21:00', 'Yiu Tung': '08:00-21:30', 'Sun Sing': '08:30-22:00', 'Harmony Place': '08:30-21:00', 'Aldrich Garden': '08:00-21:30', 'Perfect Mount': '08:00-23:00', 'Fung Wah': '08:00-20:30', 'Hing Wah': '09:00-20:30', 'Ko Way': '08:30-21:30', 'Winner': '09:00-20:00', 'Wan Tsui': '08:00-22:00', 'Siu Sai Wan': '08:00-23:00'}

In [12]:
open_24h = LiYingjie_25D027_WELLCOME_DF[LiYingjie_25D027_WELLCOME_DF["Operating_Hours"].str.contains("24 Hours", na=False)]
print(open_24h)

Empty DataFrame
Columns: [Store Name, Address, Floor, Number, Operating_Hours, Building_Name]
Index: []

In [13]:
LiYingjie_25D027_WELLCOME_DF.iloc[:,[0,2,4]]

              Store Name                                Floor Operating_Hours
0        Victoria Centre                                  G/F     08:00-22:00
1         Mercury Street                                  G/F     08:00-22:00
2   Fortress Metro Tower                                  G/F     08:00-23:00
3            City Garden                   30-33 Ground Floor     08:30-22:00
4            North Point                                  G/F     08:00-22:00
5              Metropole                  Portion of Basement     08:00-23:00
6           Island Lodge                                 G/F      08:30-22:00
7                Fitfort                                 G/F      08:30-22:01
8        Healthy Village                      (Portion), UG/F     08:00-22:00
9              Gold Luck                   Upper Ground Floor     08:00-23:00
10             Park Vale                    Upper Grond Floor     08:00-23:00
11              Kornhill                                  G/F     08:00-21:00
12              Tai Shan                                  G/F     08:00-22:00
13            Upper East                                  G/F     08:30-21:30
14       Tai On Building  G26 - G31 (Portion) on Ground Floor     08:00-22:00
15          Lei King Wan                              GC19-21     08:00-21:00
16              Yiu Tung         S6A, S6B& S6C (partion), G/F     08:00-21:30
17              Sun Sing                            G/F & M/F     08:30-22:00
18         Harmony Place                                  2/F     08:30-21:00
19        Aldrich Garden                                  1/F     08:00-21:30
20         Perfect Mount                                  G/F     08:00-23:00
21              Fung Wah                                 G/F      08:00-20:30
22              Hing Wah                Upper Floor (portion)     09:00-20:30
23                Ko Way                                  1/F     08:30-21:30
24                Winner                             Basement     09:00-20:00
25              Wan Tsui                                  3/F     08:00-22:00
26           Siu Sai Wan                                  2/F     08:00-23:00

In [18]:
c.columns

Index(['Store Name', 'Address', 'Floor', 'Number', 'Operating_Hours',
       'Building_Name'],
      dtype='object')

In [21]:
LiYingjie_25D027_WELLCOME_DF["Area"]="Hong Kong Island"
print(LiYingjie_25D027_WELLCOME_DF)

              Store Name                                            Address  \
0        Victoria Centre               No.15 Watson Road, North Point, H.K.
1         Mercury Street               28 Mercury Street, North Point, H.K.
2   Fortress Metro Tower                              238 King’s Road, H.K.
3            City Garden  7-14 , City Garden , No. 233 Electrial Road , ...
4            North Point                 338 King's Road, North Point, H.K.
5              Metropole         No. 416-426 King's Road, North Point, H.K.
6           Island Lodge               61 & 63 Marble Rd, North Point, H.K.
7                Fitfort                 560 King's Road, North Point, H.K.
8        Healthy Village           188 Tsat Tsz Mui Road, North Point, H.K.
9              Gold Luck              989-992 King's Road, Quarry Bay, H.K.
10             Park Vale              No.1060 King's Road, Quarry Bay, H.K.
11              Kornhill               18 Hong Shing Street, Kornhill, H.K.
12              Tai Shan                           Tai Koo Shing, Hong Kong
13            Upper East               18 Shing On Street, Sai Wan Ho, H.K.
14       Tai On Building                  No. 57/87 Shau Kei Wan Road, H.K.
15          Lei King Wan               35 Tai Hong Street, Sai Wan Ho, H.K.
16              Yiu Tung                 12 Yiu Hing Road, Shaukeiwan, H.K.
17              Sun Sing          245-247 Shaukeiwan Road, Shaukeiwan, H.K.
18         Harmony Place                        333 Shau Kei Wan Road, H.K.
19        Aldrich Garden             No.2 Oi Lai Street, Shau Kei Wan, H.K.
20         Perfect Mount                  1 Po Man Street, Shaukeiwan, H.K.
21              Fung Wah                    Fung Wah Estate, Chai Wan, H.K.
22              Hing Wah                 Hing Wah Estate II, Chai Wan, H.K.
23                Ko Way                         No 111 Chai Wan Road, H.K.
24                Winner                            333 Chai Wan Road, H.K.
25              Wan Tsui                    Wan Tsui Estate, Chai Wan, H.K.
26           Siu Sai Wan  Siu Sai Wan Estate, Siu Sai Wan Road, Chai Wan...

                                  Floor     Number Operating_Hours  \
0                                   G/F  3105 1578     08:00-22:00
1                                   G/F  2571 4869     08:00-22:00
2                                   G/F  2571 6421     08:00-23:00
3                    30-33 Ground Floor  3580 7319     08:30-22:00
4                                   G/F  2508 6197     08:00-22:00
5                   Portion of Basement  2564 0803     08:00-23:00
6                                  G/F   2814 8365     08:30-22:00
7                                  G/F   3583 4260     08:30-22:01
8                       (Portion), UG/F  2214 0344     08:00-22:00
9                    Upper Ground Floor  2115 9934     08:00-23:00
10                    Upper Grond Floor  2109 3393     08:00-23:00
11                                  G/F  2885 0337     08:00-21:00
12                                  G/F  2885 3216     08:00-22:00
13                                  G/F  2567 1021     08:30-21:30
14  G26 - G31 (Portion) on Ground Floor  2576 5708     08:00-22:00
15                              GC19-21  2815 6029     08:00-21:00
16         S6A, S6B& S6C (partion), G/F  2663 4818     08:00-21:30
17                            G/F & M/F  2567 1325     08:30-22:00
18                                  2/F  2997 9423     08:30-21:00
19                                  1/F  2818 5837     08:00-21:30
20                                  G/F  2567 1549     08:00-23:00
21                                 G/F   2505 2734     08:00-20:30
22                Upper Floor (portion)  2558 2909     09:00-20:30
23                                  1/F  2558 9728     08:30-21:30
24                             Basement  2896 3032     09:00-20:00
25                                  3/F  2505 1446     08:00-22:00
26                                  2/F  3755 0471     08:00-23:00

                                Building_Name              Area
0                             Victoria Centre  Hong Kong Island
1                             Supernova Stand  Hong Kong Island
2                        Fortress Metro Tower  Hong Kong Island
3               Commerial Podiums Below Block  Hong Kong Island
4               Two Chinachem Exchange Square  Hong Kong Island
5                          Metropole Building  Hong Kong Island
6                                Island Lodge  Hong Kong Island
7                                     Fitfort  Hong Kong Island
8               Healthy Village I Development  Hong Kong Island
9                                   Gold Luck  Hong Kong Island
10                                  Park Vale  Hong Kong Island
11                             Kornhill Plaza  Hong Kong Island
12                           Tin Shan Mansion  Hong Kong Island
13                              18 Upper East  Hong Kong Island
14                            Tai On Building  Hong Kong Island
15                               Lei King Wan  Hong Kong Island
16  Yiu Tung Shopping Centre, Yiu Tung Estate  Hong Kong Island
17                          Sun Sing Building  Hong Kong Island
18                              Harmony Place  Hong Kong Island
19                             Sldrich garden  Hong Kong Island
20                       Perfect Mount Garden  Hong Kong Island
21                             Hiu Fung House  Hong Kong Island
22                           Restaurant Block  Hong Kong Island
23                              Eastern Plaza  Hong Kong Island
24                              Winner Centre  Hong Kong Island
25                Wan Tsui Commercial Complex  Hong Kong Island
26                          Siu Sai Wan Plaza  Hong Kong Island

In [24]:
LiYingjie_25D027_WELLCOME_DF.to_csv("LiYingjie_25D027_abc.csv")