<a href="https://colab.research.google.com/github/LiYingjie-21/WELLCOME-shop-information-analysis/blob/main/%E6%AC%A2%E8%BF%8E%E4%BD%BF%E7%94%A8_Colab.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Q2

In [21]:
import pandas as pd
df=pd.read_excel("/content/LiYingjie_25D027_12flavors_Store _Information.xlsx")
Tflavors_LiYingjie_25D027_DF=df
df

,Branch_Name,Address,Floor_Number,M_F_Operating_Hours ，W_PH_Operating_Hours,Telephone,Staff_Break_Hours
0,十二味（中環德己立街）,中環德己立街21號地舖,G,11:30-16:00；17:00-22:00,63660242,16：00-17：00，22：00-11：30
1,十二味 (堅尼地城),堅尼地城卑路乍街13號珍珠閣地下2-4號舖,G,11:30-15:45；17:00-22:15週一-週五； 週末及公眾假期 11:30-22:15,67901070,周一-周五 15：45-17：00 周末及公衆假日22：15-11：30
2,十二味熱辣火鍋莊（西營盤）,西環皇后大道西399-401號利時大廈地鋪,G,11:00-15:30; 17:00-22:15 週一-週五；週末及公眾假期 11:00-2...,54984845,周一-周五15：30-17：00 周末及公衆假期 22：15-11：00
3,十二味 (北角）,北角和富道21-53號和富地下G20-21號舖,G,11:00-16:00; 17:00-22:00 週一-週四；週五-週日及公眾假期 11:0...,95607594,周一-周四16：00-17：00 周五-周日及公衆假期22：00-11：00
4,十二味 (香港仔中心4期),香港仔南寧街11號香港仔中心4期地下7號,G,11:00-16:00; 17:30-22:00週一-週五；週末及公眾假期 11:00-22:00,62760901,周一-周五16：00-17：30 周末及公衆假期22：00-11：00
5,十二味 (旺角文華商場),九龍旺角砵蘭街240-244號旺角文華商場5樓B室,5,11:30-16:00; 17:00-22:00週一-週五；週末及公眾假期 11:30-22:00,65022791,周一-周五16：00-17：00 周末及公衆假期22：00-11：30
6,十二味 (尖沙咀),尖沙咀赫德道1-3A號利威商業大廈地下6號舖及1樓,G&1,11:30-16:00; 17:00-22:30週一-週五；週末及公眾假期 11:30-22:30,26121298 / 26121228,周一-周五16：00-17：00 周末及公衆假期22：30-11：30
7,十二味 (荔枝角),"九龍荔枝角長義街15號 D2 Place 2期2樓Shops 212B, 213, 216A鋪",2,11:00-16:30; 17:30-22:00週一-週五；週末及公眾假期 11:00-22:00,65023560,周一-周五16：30-17：30 周末及公衆假期22：00-11：00
8,十二味（奧海城二期）,大角咀海庭道18號奧海城2期1樓146B號舖,1,11:00-16:00; 17:00-22:00週一-週五；週末及公眾假期 11:00-22:00,51219526,周一-周五16：00-17：00 周末及公衆假期 22：00-11：00
9,十二味 (觀塘),觀塘協和街33號裕民坊YM² 3樓308號舖,3,11:00-16:00; 17:00-22:00週一-週四；週五-週日及公眾假期 11:00...,97879060,周一-周四16：00-17：00 周五-周日及公衆假期22：00-11：00
10,十二味 (黃大仙中心南館),黃大仙正德街103號黃大仙中心南館1樓101號舖,1,11:00-16:00; 17:00-21:30週一-週四；週五-週日及公眾假期 11:00...,63672412,周一-周四16：00-17：00 周五-周日及公衆假期21：30-11：00
11,十二味 (啟德),九龍城沐泰街9號嘉峯匯1樓10號舖,1,11:00-16:00; 17:30-22:00週一-週五；週末及公眾假期 11:00-22:00,67900755,周一-周五16：00-17：30 周末及公衆假期 22：00-11：00
12,十二味 (青衣城二期),青衣青敬路31號青衣城二期2樓224號舖,2,11:00-16:00； 17:00-22:00週一-週五；週末及公眾假期 11:00-22:00,26682115,周一-周五16：00-17：00 周末及公衆假期22：00-11：00
13,十二味 (屯門卓爾廣場),屯門石排頭徑1號卓爾廣場地下G1B號舖,G,11:00-16:00; 17:00-22:00週一-週四；週五-週日及公眾假期 11:00...,​ 67900865,周一-周四16：00-17：00 周五-周日及公衆假期22：00-11：00
14,十二味 (石門京瑞廣場),沙田安群街1號京瑞廣場2期地下G17&43號舖,G,11:00-16:30; 17:30-22:30週一-週五；週末及公眾假期 11:00-22:30,94891596,周一-周五16：30-17：30 周末及公衆假期22：30-11：00
15,十二味 (將軍澳中心）,將軍澳唐德街9號將軍澳中心B樓B15號舖,G,11:30-16:00; 17:00-21:45週一-週四；週五-週日及公眾假期 11:30...,63661242,周一-周四16：00-17：00 周末及公衆假期21：45-11：30
16,十二味 (大圍),大圍村南道45-47號搵食市集1樓11號舖,1,11:30-16:00; 17:00-22:30週一-週五，週末及公眾假期 11:30-22:30,55395811,周一-周五16：00-17：00 周末及公衆假期22：30-11：30

Q3

In [25]:
import numpy as np
LiYingjie_25D027_Tflavors_NP=np.array(Tflavors_LiYingjie_25D027_DF["Branch_Name"])
print(LiYingjie_25D027_Tflavors_NP)

['十二味（中環德己立街）' '十二味 (堅尼地城)' '十二味熱辣火鍋莊（西營盤）' '十二味 (北角）' '十二味 (香港仔中心4期)'
 '十二味 (旺角文華商場)' '十二味 (尖沙咀)' '十二味 (荔枝角)' '十二味（奧海城二期）' '十二味 (觀塘)'
 '十二味 (黃大仙中心南館)' '十二味 (啟德)' '十二味 (青衣城二期)' '十二味 (屯門卓爾廣場)' '十二味 (石門京瑞廣場)'
 '十二味 (將軍澳中心）' '十二味 (大圍)']

Q4

In [24]:
namelist=[Tflavors_LiYingjie_25D027_DF["Branch_Name"]]
hourlist=[Tflavors_LiYingjie_25D027_DF["M_F_Operating_Hours ，W_PH_Operating_Hours"]]
LiYingjie_25D027_dict={"Store names":namelist,"Operating Hours":hourlist}
print(LiYingjie_25D027_dict)

{'Store names': [0       十二味（中環德己立街）
1        十二味 (堅尼地城)
2     十二味熱辣火鍋莊（西營盤）
3          十二味 (北角）
4     十二味 (香港仔中心4期)
5      十二味 (旺角文華商場)
6         十二味 (尖沙咀)
7         十二味 (荔枝角)
8        十二味（奧海城二期）
9          十二味 (觀塘)
10    十二味 (黃大仙中心南館)
11         十二味 (啟德)
12      十二味 (青衣城二期)
13     十二味 (屯門卓爾廣場)
14     十二味 (石門京瑞廣場)
15      十二味 (將軍澳中心）
16         十二味 (大圍)
Name: Branch_Name, dtype: object], 'Operating Hours': [0                               11:30-16:00；17:00-22:00
1     11:30-15:45；17:00-22:15週一-週五； 週末及公眾假期 11:30-22:15
2     11:00-15:30; 17:00-22:15 週一-週五；週末及公眾假期 11:00-2...
3     11:00-16:00; 17:00-22:00 週一-週四；週五-週日及公眾假期 11:0...
4     11:00-16:00; 17:30-22:00週一-週五；週末及公眾假期 11:00-22:00
5     11:30-16:00; 17:00-22:00週一-週五；週末及公眾假期 11:30-22:00
6     11:30-16:00; 17:00-22:30週一-週五；週末及公眾假期 11:30-22:30
7     11:00-16:30; 17:30-22:00週一-週五；週末及公眾假期 11:00-22:00
8     11:00-16:00; 17:00-22:00週一-週五；週末及公眾假期 11:00-22:00
9     11:00-16:00; 17:00-22:00週一-週四；週五-週日及公眾假期 11:00...
10    11:00-16:00; 17:00-21:30週一-週四；週五-週日及公眾假期 11:00...
11    11:00-16:00; 17:30-22:00週一-週五；週末及公眾假期 11:00-22:00
12    11:00-16:00； 17:00-22:00週一-週五；週末及公眾假期 11:00-22:00
13    11:00-16:00; 17:00-22:00週一-週四；週五-週日及公眾假期 11:00...
14    11:00-16:30; 17:30-22:30週一-週五；週末及公眾假期 11:00-22:30
15    11:30-16:00; 17:00-21:45週一-週四；週五-週日及公眾假期 11:30...
16    11:30-16:00; 17:00-22:30週一-週五，週末及公眾假期 11:30-22:30
Name: M_F_Operating_Hours ，W_PH_Operating_Hours, dtype: object]}

Q5

In [23]:
df[Tflavors_LiYingjie_25D027_DF['M_F_Operating_Hours ，W_PH_Operating_Hours'].str.startswith('11:00')]

,Branch_Name,Address,Floor_Number,M_F_Operating_Hours ，W_PH_Operating_Hours,Telephone,Staff_Break_Hours
2,十二味熱辣火鍋莊（西營盤）,西環皇后大道西399-401號利時大廈地鋪,G,11:00-15:30; 17:00-22:15 週一-週五；週末及公眾假期 11:00-2...,54984845,周一-周五15：30-17：00 周末及公衆假期 22：15-11：00
3,十二味 (北角）,北角和富道21-53號和富地下G20-21號舖,G,11:00-16:00; 17:00-22:00 週一-週四；週五-週日及公眾假期 11:0...,95607594,周一-周四16：00-17：00 周五-周日及公衆假期22：00-11：00
4,十二味 (香港仔中心4期),香港仔南寧街11號香港仔中心4期地下7號,G,11:00-16:00; 17:30-22:00週一-週五；週末及公眾假期 11:00-22:00,62760901,周一-周五16：00-17：30 周末及公衆假期22：00-11：00
7,十二味 (荔枝角),"九龍荔枝角長義街15號 D2 Place 2期2樓Shops 212B, 213, 216A鋪",2,11:00-16:30; 17:30-22:00週一-週五；週末及公眾假期 11:00-22:00,65023560,周一-周五16：30-17：30 周末及公衆假期22：00-11：00
8,十二味（奧海城二期）,大角咀海庭道18號奧海城2期1樓146B號舖,1,11:00-16:00; 17:00-22:00週一-週五；週末及公眾假期 11:00-22:00,51219526,周一-周五16：00-17：00 周末及公衆假期 22：00-11：00
9,十二味 (觀塘),觀塘協和街33號裕民坊YM² 3樓308號舖,3,11:00-16:00; 17:00-22:00週一-週四；週五-週日及公眾假期 11:00...,97879060,周一-周四16：00-17：00 周五-周日及公衆假期22：00-11：00
10,十二味 (黃大仙中心南館),黃大仙正德街103號黃大仙中心南館1樓101號舖,1,11:00-16:00; 17:00-21:30週一-週四；週五-週日及公眾假期 11:00...,63672412,周一-周四16：00-17：00 周五-周日及公衆假期21：30-11：00
11,十二味 (啟德),九龍城沐泰街9號嘉峯匯1樓10號舖,1,11:00-16:00; 17:30-22:00週一-週五；週末及公眾假期 11:00-22:00,67900755,周一-周五16：00-17：30 周末及公衆假期 22：00-11：00
12,十二味 (青衣城二期),青衣青敬路31號青衣城二期2樓224號舖,2,11:00-16:00； 17:00-22:00週一-週五；週末及公眾假期 11:00-22:00,26682115,周一-周五16：00-17：00 周末及公衆假期22：00-11：00
13,十二味 (屯門卓爾廣場),屯門石排頭徑1號卓爾廣場地下G1B號舖,G,11:00-16:00; 17:00-22:00週一-週四；週五-週日及公眾假期 11:00...,​ 67900865,周一-周四16：00-17：00 周五-周日及公衆假期22：00-11：00
14,十二味 (石門京瑞廣場),沙田安群街1號京瑞廣場2期地下G17&43號舖,G,11:00-16:30; 17:30-22:30週一-週五；週末及公眾假期 11:00-22:30,94891596,周一-周五16：30-17：30 周末及公衆假期22：30-11：00

Q6

In [22]:
Tflavors_LiYingjie_25D027_DF.iloc[:,[1,3,5]]

,Address,M_F_Operating_Hours ，W_PH_Operating_Hours,Staff_Break_Hours
0,中環德己立街21號地舖,11:30-16:00；17:00-22:00,16：00-17：00，22：00-11：30
1,堅尼地城卑路乍街13號珍珠閣地下2-4號舖,11:30-15:45；17:00-22:15週一-週五； 週末及公眾假期 11:30-22:15,周一-周五 15：45-17：00 周末及公衆假日22：15-11：30
2,西環皇后大道西399-401號利時大廈地鋪,11:00-15:30; 17:00-22:15 週一-週五；週末及公眾假期 11:00-2...,周一-周五15：30-17：00 周末及公衆假期 22：15-11：00
3,北角和富道21-53號和富地下G20-21號舖,11:00-16:00; 17:00-22:00 週一-週四；週五-週日及公眾假期 11:0...,周一-周四16：00-17：00 周五-周日及公衆假期22：00-11：00
4,香港仔南寧街11號香港仔中心4期地下7號,11:00-16:00; 17:30-22:00週一-週五；週末及公眾假期 11:00-22:00,周一-周五16：00-17：30 周末及公衆假期22：00-11：00
5,九龍旺角砵蘭街240-244號旺角文華商場5樓B室,11:30-16:00; 17:00-22:00週一-週五；週末及公眾假期 11:30-22:00,周一-周五16：00-17：00 周末及公衆假期22：00-11：30
6,尖沙咀赫德道1-3A號利威商業大廈地下6號舖及1樓,11:30-16:00; 17:00-22:30週一-週五；週末及公眾假期 11:30-22:30,周一-周五16：00-17：00 周末及公衆假期22：30-11：30
7,"九龍荔枝角長義街15號 D2 Place 2期2樓Shops 212B, 213, 216A鋪",11:00-16:30; 17:30-22:00週一-週五；週末及公眾假期 11:00-22:00,周一-周五16：30-17：30 周末及公衆假期22：00-11：00
8,大角咀海庭道18號奧海城2期1樓146B號舖,11:00-16:00; 17:00-22:00週一-週五；週末及公眾假期 11:00-22:00,周一-周五16：00-17：00 周末及公衆假期 22：00-11：00
9,觀塘協和街33號裕民坊YM² 3樓308號舖,11:00-16:00; 17:00-22:00週一-週四；週五-週日及公眾假期 11:00...,周一-周四16：00-17：00 周五-周日及公衆假期22：00-11：00
10,黃大仙正德街103號黃大仙中心南館1樓101號舖,11:00-16:00; 17:00-21:30週一-週四；週五-週日及公眾假期 11:00...,周一-周四16：00-17：00 周五-周日及公衆假期21：30-11：00
11,九龍城沐泰街9號嘉峯匯1樓10號舖,11:00-16:00; 17:30-22:00週一-週五；週末及公眾假期 11:00-22:00,周一-周五16：00-17：30 周末及公衆假期 22：00-11：00
12,青衣青敬路31號青衣城二期2樓224號舖,11:00-16:00； 17:00-22:00週一-週五；週末及公眾假期 11:00-22:00,周一-周五16：00-17：00 周末及公衆假期22：00-11：00
13,屯門石排頭徑1號卓爾廣場地下G1B號舖,11:00-16:00; 17:00-22:00週一-週四；週五-週日及公眾假期 11:00...,周一-周四16：00-17：00 周五-周日及公衆假期22：00-11：00
14,沙田安群街1號京瑞廣場2期地下G17&43號舖,11:00-16:30; 17:30-22:30週一-週五；週末及公眾假期 11:00-22:30,周一-周五16：30-17：30 周末及公衆假期22：30-11：00
15,將軍澳唐德街9號將軍澳中心B樓B15號舖,11:30-16:00; 17:00-21:45週一-週四；週五-週日及公眾假期 11:30...,周一-周四16：00-17：00 周末及公衆假期21：45-11：30
16,大圍村南道45-47號搵食市集1樓11號舖,11:30-16:00; 17:00-22:30週一-週五，週末及公眾假期 11:30-22:30,周一-周五16：00-17：00 周末及公衆假期22：30-11：30

Q7

In [26]:
Tflavors_LiYingjie_25D027_DF.columns

Index(['Branch_Name', 'Address', ' Floor_Number',
       'M_F_Operating_Hours ，W_PH_Operating_Hours', 'Telephone',
       'Staff_Break_Hours'],
      dtype='object')

Q8

In [27]:
Tflavors_LiYingjie_25D027_DF["Area"]="Kowloon/NT/HK island"
print(Tflavors_LiYingjie_25D027_DF)

      Branch_Name                                          Address  \
0     十二味（中環德己立街）                                      中環德己立街21號地舖
1      十二味 (堅尼地城)                            堅尼地城卑路乍街13號珍珠閣地下2-4號舖
2   十二味熱辣火鍋莊（西營盤）                            西環皇后大道西399-401號利時大廈地鋪
3        十二味 (北角）                          北角和富道21-53號和富地下G20-21號舖
4   十二味 (香港仔中心4期)                             香港仔南寧街11號香港仔中心4期地下7號
5    十二味 (旺角文華商場)                        九龍旺角砵蘭街240-244號旺角文華商場5樓B室
6       十二味 (尖沙咀)                        尖沙咀赫德道1-3A號利威商業大廈地下6號舖及1樓
7       十二味 (荔枝角)  九龍荔枝角長義街15號 D2 Place 2期2樓Shops 212B, 213, 216A鋪
8      十二味（奧海城二期）                           大角咀海庭道18號奧海城2期1樓146B號舖
9        十二味 (觀塘)                           觀塘協和街33號裕民坊YM² 3樓308號舖
10  十二味 (黃大仙中心南館)                         黃大仙正德街103號黃大仙中心南館1樓101號舖
11       十二味 (啟德)                                九龍城沐泰街9號嘉峯匯1樓10號舖
12    十二味 (青衣城二期)                             青衣青敬路31號青衣城二期2樓224號舖
13   十二味 (屯門卓爾廣場)                              屯門石排頭徑1號卓爾廣場地下G1B號舖
14   十二味 (石門京瑞廣場)                          沙田安群街1號京瑞廣場2期地下G17&43號舖
15    十二味 (將軍澳中心）                             將軍澳唐德街9號將軍澳中心B樓B15號舖
16       十二味 (大圍)                            大圍村南道45-47號搵食市集1樓11號舖

    Floor_Number          M_F_Operating_Hours ，W_PH_Operating_Hours  \
0              G                            11:30-16:00；17:00-22:00
1              G  11:30-15:45；17:00-22:15週一-週五； 週末及公眾假期 11:30-22:15
2              G  11:00-15:30; 17:00-22:15 週一-週五；週末及公眾假期 11:00-2...
3              G  11:00-16:00; 17:00-22:00 週一-週四；週五-週日及公眾假期 11:0...
4              G  11:00-16:00; 17:30-22:00週一-週五；週末及公眾假期 11:00-22:00
5              5  11:30-16:00; 17:00-22:00週一-週五；週末及公眾假期 11:30-22:00
6            G&1  11:30-16:00; 17:00-22:30週一-週五；週末及公眾假期 11:30-22:30
7              2  11:00-16:30; 17:30-22:00週一-週五；週末及公眾假期 11:00-22:00
8              1  11:00-16:00; 17:00-22:00週一-週五；週末及公眾假期 11:00-22:00
9              3  11:00-16:00; 17:00-22:00週一-週四；週五-週日及公眾假期 11:00...
10             1  11:00-16:00; 17:00-21:30週一-週四；週五-週日及公眾假期 11:00...
11             1  11:00-16:00; 17:30-22:00週一-週五；週末及公眾假期 11:00-22:00
12             2  11:00-16:00； 17:00-22:00週一-週五；週末及公眾假期 11:00-22:00
13             G  11:00-16:00; 17:00-22:00週一-週四；週五-週日及公眾假期 11:00...
14             G  11:00-16:30; 17:30-22:30週一-週五；週末及公眾假期 11:00-22:30
15             G  11:30-16:00; 17:00-21:45週一-週四；週五-週日及公眾假期 11:30...
16             1  11:30-16:00; 17:00-22:30週一-週五，週末及公眾假期 11:30-22:30

                        Telephone                       Staff_Break_Hours  \
0                        63660242                 16：00-17：00，22：00-11：30
1                        67901070    周一-周五 15：45-17：00 周末及公衆假日22：15-11：30
2                        54984845    周一-周五15：30-17：00 周末及公衆假期 22：15-11：00
3                        95607594  周一-周四16：00-17：00 周五-周日及公衆假期22：00-11：00
4                        62760901     周一-周五16：00-17：30 周末及公衆假期22：00-11：00
5                        65022791     周一-周五16：00-17：00 周末及公衆假期22：00-11：30
6             26121298 / 26121228     周一-周五16：00-17：00 周末及公衆假期22：30-11：30
7                        65023560     周一-周五16：30-17：30 周末及公衆假期22：00-11：00
8                        51219526    周一-周五16：00-17：00 周末及公衆假期 22：00-11：00
9                        97879060  周一-周四16：00-17：00 周五-周日及公衆假期22：00-11：00
10                       63672412  周一-周四16：00-17：00 周五-周日及公衆假期21：30-11：00
11                       67900755    周一-周五16：00-17：30 周末及公衆假期 22：00-11：00
12                       26682115     周一-周五16：00-17：00 周末及公衆假期22：00-11：00
13  ​                    67900865  周一-周四16：00-17：00 周五-周日及公衆假期22：00-11：00
14                       94891596     周一-周五16：30-17：30 周末及公衆假期22：30-11：00
15                       63661242     周一-周四16：00-17：00 周末及公衆假期21：45-11：30
16                       55395811     周一-周五16：00-17：00 周末及公衆假期22：30-11：30

                    Area
0   Kowloon/NT/HK island
1   Kowloon/NT/HK island
2   Kowloon/NT/HK island
3   Kowloon/NT/HK island
4   Kowloon/NT/HK island
5   Kowloon/NT/HK island
6   Kowloon/NT/HK island
7   Kowloon/NT/HK island
8   Kowloon/NT/HK island
9   Kowloon/NT/HK island
10  Kowloon/NT/HK island
11  Kowloon/NT/HK island
12  Kowloon/NT/HK island
13  Kowloon/NT/HK island
14  Kowloon/NT/HK island
15  Kowloon/NT/HK island
16  Kowloon/NT/HK island

Q9

In [28]:
Tflavors_LiYingjie_25D027_DF.to_csv("LiYingjie_25D027_abc.csv")